preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 170
  max_depth: 15
  min_samples_split: 9
  min_samples_leaf: 2
  max_features: 0.7
  random_state: 42

evaluate:
  threshold: 0.5
