preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 80
  max_depth: 20
  min_samples_split: 6
  min_samples_leaf: 2
  max_features: log2
  random_state: 42

evaluate:
  threshold: 0.5
