preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 200
  max_depth: 25
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: 0.4
  random_state: 42

evaluate:
  threshold: 0.5
