preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 240
  max_depth: 18
  min_samples_split: 10
  min_samples_leaf: 5
  max_features: log2
  random_state: 42

evaluate:
  threshold: 0.5
