preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 180
  max_depth: 14
  min_samples_split: 6
  min_samples_leaf: 3
  max_features: log2
  random_state: 42

evaluate:
  threshold: 0.5
