preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 185
  max_depth: 15
  min_samples_split: 7
  min_samples_leaf: 4
  max_features: 0.65
  random_state: 42

evaluate:
  threshold: 0.5
