preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 200
  max_depth: 16
  min_samples_split: 8
  min_samples_leaf: 2
  max_features: sqrt
  random_state: 42

evaluate:
  threshold: 0.5
