preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 120
  max_depth: 10
  min_samples_split: 15
  min_samples_leaf: 7
  max_features: log2
  random_state: 42

evaluate:
  threshold: 0.5
