preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 190
  max_depth: 13
  min_samples_split: 7
  min_samples_leaf: 2
  max_features: log2
  random_state: 42

evaluate:
  threshold: 0.5
