preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 300
  max_depth: 15
  min_samples_split: 5
  min_samples_leaf: 1
  max_features: sqrt
  random_state: 42

evaluate:
  threshold: 0.5
