preprocess:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 130
  max_depth: 11
  min_samples_split: 6
  min_samples_leaf: 3
  max_features: 0.55
  random_state: 42

evaluate:
  threshold: 0.5
